name: First automatic test

on: [push]
jobs:
  build-and-run:
    name: Build and Run
    runs-on: ubuntu-latest
    steps:
      - name: Nominal Run
        run: npm run back
        # with:
        #   node-version: 13.14
      - name: User back testing
        run: npm run testback
        # with:
        #   node-version: 13.14        