name: First automatic test

on: [push]
  # push:
  #   branches: [dev]

jobs:
  build-and-run:
    name: Build and Run
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v1
      #   with: Build Code
        node-version: 13.14
        run: npm run dev &
        name: Nominal Run
        run: node ./front/automaticTesting/testUser.js
        name: User back testing

  # deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/wtf
  #       with:
  #       node-version: 13.14
  #       run: npm run dev