name: First automatic test

on: [push]
jobs:
  build-and-run:
    name: Build and Run
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Nominal Run
        run: npm run back
        # with:
        #   node-version: 13.14
      - name: User back testing
        run: npm run testback
        # with:
        #   node-version: 13.14        